%Yamilet Casanova

pr(0027-1,['¿Que es un algoritmo?'],['Un algoritmo es un conjunto finito de instrucciones precisas que resuelven un problema o realizan un cálculo'], 20/20, ['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf ']).
pr(0027-2,['Definicion de complejidad computacional'],['Recursos computacionales que se necesitann para usar este algoritmo en la resolución de un problema de un tamaño específico. Para medir la complejidad de un algoritmo utilizaremos las notaciones O y Q'], 20/20, ['Casanova  basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
pr(0027-3,['Complejidad en tiempo'],['número de operaciones que tiene que realizar el algoritmo. Se describe en términos del número de operaciones requeridas, en lugar del tiempo de cálculo real, ya que distintos ordenadores necesitan tiempos diferentes para realizar la misma operación básica.'], 20/20, ['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
pr(0027-4,['Complejidad para obtener el mayor elemento de un conjunto'],['Usamos como medida el número de comparaciones que es la operacio básica usada en este ejemplo, el algortimo consiste el fijar al principio el primer elemento de la lista como el mayor numero, se realiza una comparación para determinar si se ha llegado al final de la lista y otra comparando el primer elemento y el segundo elemento de la lista, actualizando el valor del máximo si el segundo término es mayor que el primero, y asi sucesivamente con el resto de los elementos de la lista. Como se hacen dos comparacionesdesde el segundo hasta el n-ésimo, y una más para salir del bucle cuando i = n +1,serealizan exactamente 2(n – 1) + 1 = 2n – 1 comparaciones. Por tanto, este algoritmo es Q(n), donde n es el número de elementos de “Conjunto”.'], 20/20,['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
pr(0027-5,['Analisis de complejidad: peor caso'],['se basa en el el mayor número de operaciones que hace falta para resolver el problema dado usando el algoritmo para unos datos de entrada de un tamaño fijado.'], 20/20, ['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
pr(0027-6,['Analisis de complejidad: caso promedio'],['Se busca el número promedio de operaciones realizadas para resolver un problema considerando todas las posibles entradas de un tamaño fijo.'], 20/20, ['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
%pr(0027-7,['Ejemplo caso promedio'],['Búsqueda lineal: El comportamiento del algoritmo suponiendo que x está en la lista: Si x está hay n posibles soluciones. Si x es elprimer elemento, necesitamos tres comparaciones (una para comprobar si se ha alcanzado el final, otra para comparar x con el elemento y otra fuera del bucle). Si x es el segundo se necesitan dos más y así sucesivamente. Por tanto el número promedio es:(3+5+7+..+(2n+1))/n, luego tenemos que esto sera igual a [2(1+2+3+...+n)+n]/n, generalizando tenemos [2(n(n+1)/2)+n]/n sera igual a n+2. Por tanto la complejidad es Q(n)'], 20/20, ['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
pr(0027-8,['Ejemplo peor caso'],['Busqueda lineal: la operación básica usada es la comparación. En cada paso del bucle se llevan a cabo dos comparaciones: una para ver si se ha llegado al final de la lista y otra para comparar x y el elemento ai. Finalmente, fuera del bucle se hace una comparación más. Por tanto, si x = ai, se hacen 2i+1 comparaciones. El numero maximo de comparaciones lo hacemos si x no esta en la lista, 2n+2(2n para determinar x=! ai para todo i, una para salir del bucle uy otra fuera del bucle). Por lo tanto, una busqueda lineal requiere a lo mas O(n) ccomparaciones'], 20/20, ['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
pr(0027-9,['Clase NP'],['Se dice que un problema pertenece a la clase NP si se puede comprobar en tiempo polinómico que una solución efectivamente lo es'], 20/20, ['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
pr(0027-10,['Ejemplo Ordenacion de burbuja'],['es uno de los ejemlos mas simple, pero no de los más eficientes. Damos sucesivas pasadas sobre la sucesión, intercambiando las posiciones de los elementos contiguos cuando no estén ordenados hasta que demos una pasada en la que no intercambiemos ninguna posición. Su complejidad es Q(n^2).'], 20/20, ['Casanova basado en Garcia Muñoz http://www4.ujaen.es/~magarcia/matematica_discreta/TEMA5-COMPLEJIDAD.pdf']).
pr(0027-11,['Desempeño de un algoritmo'],['Para poder analizar el desempeño de un algoritmo, debemos predecir los recursos que éste requiere, entre los que se encuentran,Cantidad de almacenamiento principal requerido por sus variables, cantidad de tráfico que genera un red de computadores, cantidad de Información que debe moverse desde y hacia las unidades de almacenamiento secundario, simplicidad del algoritmo,tiempo de cómputo'], 20/20, ['Casanova basado en el profesor Victor Bravo ']).
pr(0027-12,['Complejidad constante'],['Cuando la complejidad del algoritmo puede expresarse como una función constante T(n)=a, se dice que es constante, no depende de n.'], 20/20, ['Casanova basado en el profesorVictor Bravo']).
pr(0027-13,['Complejidad lineal'],['Cuando la complejidad de un algoritmo puede expresarse como una función lineal T(n)=an+b, donde a y b son constantes se dice que es lineal en n.'], 20/20, ['Casanova basado en el profesor Victor Bravo']).
pr(0027-14,['Complejidad cuadratica'],['cuando la complejidad de un algoritmo puede expresarse como una función cuadrática del tipo T(n)=an^2+bn+c, donde a,b y c son constantes, se dice que el algoritmo es cuadrático en n.'], 20/20, ['Casanova basado en Victor Bravo']).
pr(0027-15,['Límite asintóticos'],['El tiempo de corrida depende de la computadora en que se corra y del compilador utilizado para el programa, por ello usualmente el tiempo de corrida se expresa utilizando el orden de crecimiento o la tasa del crecimiento de este. Cuando se observa entradas de tamaño lo suficientemente grandes para que sólo el orden de crecimiento de la complejidad sea relevante, estamos estudiando la eficiencia asintótica de los algoritmos'], 20/20, ['Casanova basado en Victor Bravo']).
pr(0027-16,['La regla de la suma modificada'],['Suponga que un programa consiste en dos partes, una de las cuáles es de complejidad O(n^2) y la otra de O(n^3). En muchos casos como este, es posible sumar estas dos complejidades usando la regla de la suma: Suponga que T1(n) es de O(f1(n)), mientras que T2(n) es de O(f2(n)), además suponga que f2 no crece más rápido como f1; esto es f2 es de O(f1). Entonces podemos concluir que T1(n) + T2(n) es O(f2(n)).'], 20/20, ['Casanova basado en Victor Bravo']).
pr(0027-17,['Funcion generatriz'],['Se llaman asi a las funciones que se expresan como la suma de terminos polinomicos cuyos coeficientes son los valores del problema combinatorio que interesa, esto permino establecer relaciones entre los numeros combinatorios'], 20/20, ['Casanova basado en el  libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-18,['Diferencia entre variaciones, combinaciones y permutaciones'],['Se forma un grupo cualquiera, segun el problema y con los mismos elementos de ese grupo se intenta formar otro, si se consigue otro grupo diferente son variaciones si no son combinaciones. Tambien, cuando en un grupo entra todos los elementos y los grupos difieren en el orden, son permutaciones, si no son combinaciones'], 20/20, ['Casanova basado en el  libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-19,['Con las cifras 1,2,3,4,5 y 6 ¿Cuantos numeros de 3 cifras pueden hacerse, que sean diferentes?'],['Si formamos un numero cualquiera de 3 cifras como el 354 con los mismos elementos formamos otro como el 534, como los dos numeros son diferentes son variaciones, ya que influye el orden. Ahora disponemos de 6 elementos y solo 3 entran en cada numero. Por la ecuacion de variacion  V6,3: 6*5*4=120 numeros'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-20,['Con los numeros 1,2,3,4,5 y 6 ¿Cuantas sumas diferentes de 3 sumandos cada una pueden hacerse?'],['Formamos una suma con 3 cifras 3+5+4=12, con los mismos numeros formamos otra suma 4+5+3=12, como las dos sumas son iguales a pesar del ordden son combinaciones, disponemos de 6 elementos y 3 entran en cada grupos, aplicando la formula de combinatoria C6,3 = 6!/(3!*(6-3)!) = 20'], 20/20,['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-21,['Con las cifras 3,4,5 y 6 ¿Cuantos numeros diferentes, de cuatro cifras cada uno pueden hacerse?'],['Si formamos un numero de 4 cifras 4536 y luego con los mismos elementos formamos otro 5346, los numeros son diferentes e intervienen todos los elementos asi que es una permutacion: V4,4 = P4 = 4! = 24 numeros'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-22,['Se dispone de 4 colores diferentes. ¿Cuantos colores pueden obtenerse mezclando los 4 colores en la misma proporcion'],['Si se forma una mezcla de 4 colores y luego otra mezcla con esos 4 colores pero en diferente orden se sigue obteniendo el mismo color por lo que es una combinacion, C4,4 = 4!/4! = 1'], 20/20, ['Casanova basado en guia de combinarotia de Jacinto Davila']).
pr(0027-23,['¿Cuantas selecciones de 5 libros pueden hacerse con 12 libros diferentes?'],['De los 12 libros cada vez se toman 5 pero como no influye el orden son combinaciones C12,5 = 12!/(5!*7!) = 792 selecciones'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-24,['¿Cuantas señales pueden hacerse con 4 banderas diferentes izandolas de dos en dos?'],['No es lo mismo la señal AB que la BA, como influye el orden es una variacion. V4,2 = 4*3 = 12 señales'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-25,['En una carrera de caballos figuran 6 ejemplares. ¿De cuantas maneras diferentes pueden llegar a la meta, suponiendo que lleguen de uno en uno?'],['Como en cada grupo que se forme entran todos los elementos y no onfluye el orden es una permutación. P6 = 6! = 720 maneras'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-26,['Con cinco potes de pintura de diferentes colores. ¿Cuantos colores pueden obtenerse entrando en la formacion de cada color tre colores en la misma cantidad?'],['Si tomo en grupo con 3 colores y luego hago otro grupo con lso mismos elementos pero en orden diferentes sigo obteniendo el mismo color, es una combinacion, C5,3 = 5!/(3!*2!) = 10 colores'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-27,['En una exposicion de autos. ¿De cuantas  maneras diferentes pueden colocarse 7 coches en fila tomados de 5 en 5?'],['Como influye el orden en que se coloquen los carros es una variacion. V7,5 = 7*6*5*4*3 = 2520 maneras'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
%pr(0027-28,['Un deposito de agua tiene 7 caños de desague que arrojan 2, 3, 6, 10 y 11 litros de agua por segundo. Calcular en cuanto tiempo diferentes puede vaciarse el deposito abriendo 3 llaves cada vez.'],['Al seleccionar las 3 llaves no importa el orden en que las abra ya que el tiempo no cambia entonces sera una combinacion, C7,3 = [7!/(3!*4!)]= 35 tiempos '], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-29,['Una habitación tiene 7 puertas. ¿De cuantas maneras puede una persona entrar y salir por puertas diferentes?'],['En cada entrada y salida uso dos puetas y como influye el orden, es una variacion. V7,2 = 7*6 = 42 maneras'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
%pr(0027-30,['Se dispone de 7 pesas de diferente valor cada una. ¿Cuantas pesadas diferentes pueden hacerse tomandolas de tres en tres?'],['Una vez elegidas 3 pesas no influye el orden en que se coloquen en el peso, son combinaciones, C7,3 = [7!/(3!*4!)] = 35 pesadas'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-31,['Con los numeros 2,3,8,4 y 5, calcular cuantos numeros de 3 cifras empiezan en 5'],['Tenemos un numero de cifras xxx. Pero tiene que comenzar en 5 por lo que umero seria 5xx por lo tanto quedan 4 cifras si el numero fijo es el 5, esos 4 numeros van a variar en esos dos espacios, V4,2 = 4*3 = 12 numeros'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-32,['Con las cifras 123786. Calcular cuantos numeros de 4 cifras pueden hacerse con la condicion de que empiecen en 7 y terminen en 3.'],['Un numero de 4 cifras xxxx, pero que empiece en 7 y termine en 3 7xx3, tenemos 4 numeros para variar en los dos espacios sobrantes, V4,2 = 4*3 = 12'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-33,['Con las cifras del numero 24531 Calcular en cuantos numeros de 3 cifras interviene el numero 4'],['Tenemos un numero de 3 cifras xxx el cuatro puede ocupar 3 posiciones en ese numero (4xx, x4x, xx4), esto es la suma de la variacion de los4 nnumeros restantes en los espacios restantes. es decir es 3V4,2 = 3*4*3 = 36 numeros'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-34,['Con los numeros 3,2,7,6,4 y 0. Calcular cuantos numeros de 3 cifras pueden hacerse'],['Si un numero de 3 cifras es xxx , y en este caso influye el orden en que se colocan es una variacion V6,3 = 6*5*4 = 120. Pero de estos numeros los que comienzan por 0 no son de 3 cifras entonces hay que restarlos al resultados. V5,2 = 5*4 = 20. Finalmente 120-20 = 100 numeros'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-35,['Con las cifras 76843. Calcular cuantos numeros pares de 4 cifras pueden hacerse'],['Un numero de 4 cifras se puede representar como xxxx. De los numeros dados 6,8,4 son  pares por lo tanto hay tres posibles formas de tener el numero de 4 cifras (xxx6, xxx8, xxx4), para cada caso tenemos un variacion V4,3 = 4*3*2 = 24, ya que son 3 formas el resultado se multiplica por 3, y tenemos 72 numeros.'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-36,['Con las cifras del numero 20834. Calcular cuantos numeros pares de 3 cifras pueden hacerse.'],['Tenemos que los numeros pares son todos menos el 3 asi que hay 4 formas diferentes de formar un numero de 3 cifras (xx0, xx2, xx4, xx8), tenemos 4 variaciones de dos en dos. 4V4,2 = 4*4*3 = 48. Pero tenemos la presencia de un cero que al estar como primer elemento convierte al numero en uno de 2 cifras por lo tanto a 48 se le resta las 3  variaciones quedando solo una cifra variante, es decir, 0x2, 0x4, 0x8 la forma 0x0 no es posible ya que esta el 0 como ultimo elemento y no se repite, asi que tendremos 3V3,1 = 3*3 = 9. Finalmente 48-9= 39 numeros.'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-37,['Con las cifras del numero 34725. Calcular cuantos numeros menores de 5000 pueden hacerse.'],['Numeros de una cifra entran todos los elementos uno a la vez V5,1 = 5, de dos cifras V5,2 = 5*4 = 20, de tres cifras V5,3 = 5*4*3=60. Para el caso de 4 cifras debe ser menor a 5000 por lo tanto solo vale que la cifra comience con 2,3 y 4 resultando en 3 formas de variar 4 cifras restantes en los 3 espacios 3V4,3 = 3*4*3*2 = 72. Finalmente la suma de todas las variaciones obtenidas es el resultado 5+20+60+72= 157 numeros '], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-38,['Con las cifras del numero 21389. Calcular cuantos numeros mayores de 3000 pueden hacerse'],['El numero debe tener un minimo de 4 cifras y q comience con 3,6,9 que nos dara 3 formas de variar 4 cifras en los 3 espacios sobrantes 3V4,3 = 3*4*3*2 = 72. Luego calculamos la variacion para un numero de 5 cifras en donde entran todos los elementos sin restriccion alguna y se van a distribuir en los 5 espacios disponibles, y nos lleva a una permutacion V5,5 = P5= 5! = 120. La suma de estos dos resultados nos da 72+120 =  192 numeros. '], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-39,['Con las cifras del numero 15437. Calcular cuantos numeros pueden formarse que esten comprendidos entre 200 y 5000'],['Numero de 3 cifras mayor que 200 son 3xx, 4xx, 5xx, 7xx dond tenemos 4 formas de variar 4 cifras en los dos espacios disponibles 4V4,2 = 4*4*3 = 48, a su vez necesitamos que sean menores de 5000 dondo tendremos 1xxxx, 3xxxx, 4xxxx y observamos que tenemos 3 formas diferentes de variar 4 numeros en 3 espacios disponibles 3V4,3 =  3*4*3*2 =72. Por ultimo la suma de esto nos da el resultado que buscamos 48+72 = 120 numeros '], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-40,['Con los numeros del 1 al 9, ambos incusive. ¿Cuantos numeros de 5 cifras pueden formarse con la condicion de que las tres primeras sea pares y las dos ultimas impares'],['Tenemos un numero de 5 cifra que se vera como  PPPII siendo P numero par e I impar, si dejamos los dos impares fijos calculamos la variacion de los numeros impares que seran 3 formas diferentes 3V4,4 = 4*3*2 = 24. Ahora dejando los pares fijos tendremos als variacion de los numeros impares del 1 al 9 que son 5 cifras en los dos espacios V5,2 = 5*4 = 20. Por ultimo se multiplican los dos resultados que arrojo cada variacion 24*20 = 480 numeros'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-41,['En una reunion hay 8 mujeres y 6 hombres. Calcular cuantos grupos pueden hacerse, entrando en cada grupo 4 mujeres y 3 hombres.'],['en este caso se observa que el orden en que se colocan no influye, son combinaciones. Tenemos que el grupo es de la forma M M M M H H H, Dejando los hombres fijos calculamos las posobles combinaciones de ordenar las 8 mujeres en 4 espacios. C8,4 = 70 grupos de mujeres, y ahora si dejamos las mujeres fijas y calulamos las combinaciones de los 6 hombres en los 3 espacios tenemos C6,3 = 20 grupos de hombres. Por ultimo el producto de estos dos grupos nos da 70*20 = 1400 grupos'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-42,['Hallar los distintos grupos que ppuedenn formarse con 4 cifras y 4 letras con la condicion de que en todos, letras y numeros vayan alternados y en cada grupo entren las letras y todos los numeros.'],['La forma general de ordenar esto es de dos formas que comience con numero 1 A 2 B 3 C 4 D, o que comience con una letra A 1 B 2 C 3 D 4, Pero si ponemos atencion a la final nos dara dos formas de variar 4 numeros o 4 letras en 4 espacios disponibles V4,4 * V4,4 = (V4,4)^2 = 2P4^2 = 2*(4!)^2  = 1152'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-43,['Se dispone de 10 consonantes y 5 vocales. ¿Cuantas palabras pueden formarse sabiendo que cada palabra costa de 3 consonantes y 2 vocales?'],['La palabra tendra la forma general C C C V V como en este el orden importa son variaciones, dejando las consonantes fijas resulta V5,2 = 20, y dejando las vocales fijas tenemos V10,3 = 720. Como no se sabe la posicion que ocuparan las letras entonces estas pueden variar en la formacion de cada palabra diferente por lo que debemos calcular la V5,5 = P5 = 120 ahora el producto de estos calculos sera el resultado 20*720*120= 1728000 palabras'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-44,['¿De cuantas maneras se puede repartir 5 juguetes diferentes entre dos niños, dando dos a cada uno de ellos?'],['Como no influye el orden de colocacion so combinacion. Al primero se le pueden dar C5,2 = 10 maneras. Pero al dar dos juguetes al primeros nos quedan 3 para el segundo por lo que podemos formar dos grupos de 2 en 2 C3,2 = 3 el producto de estas dos combianciones no da 10*3 = 30 maneras'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-45,['Se dispone de 5 libros de matematicas 3 de fisica y 4 de biologia. Cada libro es de un autor diferente. Calcular de cuantas maneras se pueden colocar todos ellos en un estante.'],['Como se colocan todos e influye el orden de colocacion so permutaciones P12= 12!= 479001600'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-46,['Se dispone de 5 libros de matematicas 3 de fisica y 4 de biologia. Calcular de cuantas maneras diferentes pueden colocarse con la condicion de que los de cada materia esten siempre juntos'],['El grupo esta formado por matematicas, fisica, bilogia, podemos formar 3 grupos de permutaciones que a su vez permuta ya que la ubicacion de cada materia tambien varia. Asi tendremos (P5*P4*P4)*P3 = 5!* 3!* 4! *3! = 103680'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-47,['Se dispone de 5 libros de matematicas 3 de fisica y 4 de biologia. Calcular de cuantas maneras diferentes pueden colocarse con la condicion de que todos los de fisicas siempre esten juntos.'],['El grupo sera de la forma los de matematica y biologia en un grupo y los de fisica en otro, tenemos que son 5 de matematica y 4 de biologia que suman 9 libros que permutan P9= 9!, y los de fisica que son 3 permutan tambien P3 = 3! por lo tanto la respuesta sera 9!*3! = 2177280'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-48,['Se dispone de 5 libros de matematicas 3 de fisica y 4 de biologia.  Calcular de cuantas maneras diferentes pueden colocarse con la condicion de que el primer libro sea de fisica y el ultimo de biologia.'],['El grupo es de la forma lbro de Fisica, luego todos los libros de fisica matematica y biologia y finalmente uno de biologia. Por lo tanto puede empezar como V3,1 = 3 y terminar con V4,1=4. Y en la parte central quedan 10 libros en total que permutan por lo tanto tendremos 4*3*P10 = 4*3*10! = 43545600'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-49,['Se dispone de 5 libros de matematicas 3 de fisica y 4 de biologia.  Calcular de cuantas maneras diferentes pueden colocarse con la condicion de que todos los de matematicas siempre se encuentren juntos.'],['SI considermaos el de matematicas como un solo grupo y sumamos los de fisicas y biologia como uno solo tendremos P8 = 8!. Recordemos que el de matematicas permuta P5-= 5! tendremos 8!*5! = 4838400 '], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-50,['Se dispone de 5 libros de matematicas 3 de fisica y 4 de biologia.  Calcular de cuantas maneras diferentes pueden colocarse con la condicion de que un libro determinado de fisica y otro de matematicas nunca esten juntos'],['Si a todos lso grupos le quitamos aquellos grupos en los que los dos libros vayan juntos tendremos el problema resuelto. El numero total de grupos que podemos formar es P12= 12!, considerando como un elemento, al grupo formado por los dos libros, tendremos 11 elementos que forman P11 = 11!, pero como el grupo de lso dos libros puede formar a su vez P2 = 2! tendremos finalmente P12-P11*P2 = 12!-11!*2 = 399168000'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-51,['¿Cuantas banderas de franjas horizontales ppueden hacerse disponiendo de 5 colores?'],['Como se dispone de 5 colores hay 5 formas diferentes es decir, hacer una bandera d un color, otra de dos y asi sucesivamente por lo tanot tendremos la suma de V5,1+V5,2+V5,3+V5,4+V5,5 = 5+20+60+120+120=325 banderas'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-52,['¿De cuantas maneras puede una persona invitar a comer a 5 amigos?'],['Como no influye el orden seran las combinaciones de invitar a un amigo, a dos amigos ya si sucesivamente. Asi tendremos C5,1+C5,1+C5,3+C5,4+C5,5 = 5+10+10+5+1 = 31 maneras'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-53,['Se dispone de 16 puntos en un plano, 6 de ellos en linea recta y los demas no estan alineados 3 a 3. ¿Cuantas lineas rectas pueden trazarse?'],['Cada dos puntos determinan una recta, luego se formaran: C16,2=120 rectas. Pero como hay 6 puntos en linea hay que descontar las rectas que se pondrian formar, que son C6,2=15 Asi tendremos C16,2 - C6,2 +1 = 120-15+1 = 106 rectas.'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-54,['Se dispone de 10 rectas. 4 de las cuales son parelelas entre si. ¿En cuantos puntos se cortan?'],['Dos rectas forman un punto, y como no influye el orden de colocacion con combinaciones. Las 10 rectas forman C10,2 = 45 puntos. Pero las 4 paralelas si se cortasen formarian C4,2= 6 puntos que hay que descontar a los anteriores, C10,2-C4,2 = 45 - 6 = 39'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-55,['Calcular el numero de diagonales de un poligono de 6 lados'],['Diagonal es la recta que une dos vertices no consecutivos. Uniendo los seis vertices de dos en dos resultan C6,2 =  15 lineas, pero de esas lineas hay que descontar las que unen dos vertices consecutivos (lados). C6,2 - 6 = 9'], 20/20, ['Casanova basado en el libro de matemáticas de 5to año del Prof. E. Navarro']).
pr(0027-56,[' Representación y evaluación de Predicados'],['A diferencia de cálculo de proposiciones en cálculo de predicados utilizamos variables, dentro de este tema consideramos las expresiones booleanas que se definieron como proposiciones abiertas. En general podemos decir que un predicado puede tener una o más variables y que las variables pueden tomar valores de un conjunto específico llamado DOMINIO.  '], 20/20, ['Casanova basado en Telésforo Zamorano http://www.tesoem.edu.mx/alumnos/cuadernillos/2012.007.pdf']).
pr(0027-57,['Ejemplo de predicados'],['El libro es azul, AZ(x), AZ es el predicado: es de color azul, en el dominio de objetos. Armando y Eduardo son hermanos,H(x,y), H es el predicado: es hermano de, el dominio el conjunto de las personas. Esteban compra mercancía los lunes en Almacenes A, A(x,y), A es el predicado: comprar en los almacenes cierto día, el dominio para el primer argumento es el de las personas, el dominio del segundo son los días de la semana. '], 20/20, ['Casanova basado en Telésforo Zamorano http://www.tesoem.edu.mx/alumnos/cuadernillos/2012.007.pdf']).
pr(0027-58,['Ejemplo de cuantificadores'],['Frase en lenguaje natural Algún venezolano es medallista olímpico Se traduce en: Existe al menos un venezolano que cumple con la condición de ser medallista olímpico Las variables Existe al menos un venezolano x que cumple la condición que x es medallista olímpico'], 20/20, ['Casanova basado en el profesor Victor Bravo']).
pr(0027-59,['¿Qué es un cuantificador universal?'],['Indica que una proposición es Verdadera para todos los valores de una variable en un “universo” en particular. p(x) es verdadera, para todos los valores de x en el dominio.'], 20/20, ['Casanova basado en el profesor Victor Bravo']).
pr(0027-60,['¿Qué es un cuantificador?'],['Otra forma de crear una proposición o de cerrar una función proposicional abierta, es la Cuantificación. Una proposición abierta se cierra, si todas sus variables se cuantifican. Hay dos tipos de cuantificadores Universal y existencial'], 20/20, ['Casanova basado en el profesor Victor Bravo']).
pr(0027-61,['¿Qué es un cuantificador existencial?'],['Denota que existe “al menos” un elemento x del Universo, para el cual p(x) es verdadera.'], 20/20, ['Casanova basado en el profesor Victor Bravo']).
pr(0027-62,['Maneras de expresar un cuantificador existencial'],['Formas de expresarlo: “Hay un x” ,“Para algún x” ,“Para al menos un x”,“Existe un x tal que.Resumiendo La proposición es Verdadera, si existe al menos un elemento x del universo tal que p(x) sea verdadera. De lo contrario es falsa.' ], 20/20, ['Casanova basado en el profesor Victor Bravo']).
pr(0027-63,['Maneras de expresar un cuantificador universal'],['En lenguaje natural decimos Formas de expresarlo: “Para todo x”,“Para cada x”,“Para cualquier x”,“Para todo x y y”,“Para todo x,y”. Resumiendo la proposición es Verdadera, si para cada reemplazo de x, p(x) es verdadera. Es falsa, si existe al menos un x para el cual p(x) es falsa.'], 20/20, ['Casanova basado en el profesor Victor Bravo']).
pr(0027-64,['Ejemplo cuantificador'],['Todo estudiante de la clase de Matemáticas Discretas vive en Mérida, Se define el dominio: todas las personas, p(x) : estudiante de la clase de Matemáticas Discretas, q(x) : vive en Mérida. Frase lógica Para todo persona x, si la persona x es un estudiante de la esta clase, entonces la persona x vive en Mérida.'], 20/20, ['Casanova basado en el profesor Victor Bravo']).
pr(0027-65,['Proposición lógica'],['Expresiones que pueden ser verdaderas o falsas pero no ambas'], 20/20, ['Casanova basado en Telésforo Zamorano http://www.tesoem.edu.mx/alumnos/cuadernillos/2012.007.pdf']).
pr(0027-66,['Proposición abierta'],['Una expresión que contiene una o más variables y al sustituir las variables por valores específicos se obtiene una proposición lógica. '], 20/20, ['Casanova  basado en Telésforo Zamorano http://www.tesoem.edu.mx/alumnos/cuadernillos/2012.007.pdf']).
pr(0027-67,['Expresiones Booleanas.'],['Proposiciones lógicas y proposiciones abiertas. '], 20/20, ['Casanova  basado en Telésforo Zamorano http://www.tesoem.edu.mx/alumnos/cuadernillos/2012.007.pdf']).
pr(0027-68,['Ejemplos de funciones booleanas, abiertas y logicas'],['a) México está en América, Proposición Lógica. b) 1 < 2, Proposición Lógica, c) Hoy es lunes, Proposición Abierta, d) x + 3 = 5 Proposición Abierta, e) El 3 de abril de 1970 fue domingo, Proposición Lógica, f) Los cocodrilos pueden volar, Proposición Lógica, g)Las matemáticas son agradables, Proposición Abierta'], 20/20, ['Casanova basado en Telésforo Zamorano http://www.tesoem.edu.mx/alumnos/cuadernillos/2012.007.pdf']).
pr(0027-69,['Particion de un conjunto'],['Una partición de un conjunto está formada por subconjuntos disjuntos ningún elemento aparece en dos conjuntos tal que la unión es igual al conjunto original. '], 20/20, ['Casanova basado en Telésforo Zamorano http://www.tesoem.edu.mx/alumnos/cuadernillos/2012.007.pdf']).
pr(0027-70,['Ejemplo de subconjunto'],['El Barcelona y el Real Madrid son un subconjunto de la liga española'], 20/20, ['Casanova']).
pr(0027-71,['Relacion de recurrencia'],['Una relación de recurrencia para una sucesión A=(a0 , a1 , a2 ,...., an ,...) es una expresión que relaciona An con uno o más términos precedentes (a0 , a1 , a2 ,...., an-1) , para cualquier n entero mayor o igual que un entero inicial m. Los valores de los primeros términos necesarios para empezar a calcular se llaman condiciones iniciales '], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-72,['Recurrencias lineales y homogeneas'],['Si An = c1 an-1 +c2 an-2 + ... + cm an-m + g(n) con ∀n≥m, donde c1 ,... , cm son constantes, decimos que la relación de recurrencia es lineal y de coeficientes constantes. Si además g(n)=0 diremos que la relación es homogénea. '], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-73,['Ecuación característica de recurrencia'],['La ecuación x2 = c1 x +c2 se llama ecuación característica de la recurrencia anterior y sus raíces se llaman raíces características. Si α es raíz característica entonces αn es una solución de la relación de recurrencia. Si α es raíz doble de la ecuación característica entoncesnα^n es solución de la relación. Si T y Z son soluciones de la relación de recurrencia entonces T+Z y kT también lo son. '], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-74,['Soluciones de la relación de recurrencia'],['Si se expresa como An = (c1*An-1)+(c2*An-2) donde A0 = B0 sub cero y A1 = B1. Entonces hay dos maneras de obtener la relacion: 1) Si α y β son las raíces de la ecuación característica, α≠β, entonces la solución general de recurrencia es An = k1*α^n + k2*β^n. 2) Si α es raíz doble de la ecuación característica, entonces la solución general es An = k1*α^n + k2*n*α^n.'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-75,['Ejercicio de recurrencia'],['Se desea hallar el máximo y el mínimo del conjunto A={a1, a2, ..., an}. Se procede así (suponemos que n=2^k por simplicidad), Si n=1, entonces a1=max(A)=min(A). Si n>1, descomponemos A en dos subconjuntos A1 y A2 del mismo tamaño y resolvemos el problema para A1 y A2. Comparando max(A1) y max(A2) hallaremos max(A) y análogamente calcularemos mín(A). Llamando f(n) al numero de comparaciones efectuadas, resulta que f(n) = 2f(n/2) +2.'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-76,['Ejemplo de recurrencia'],['Si f(n) es el numero de comparaciones requeridas para buscar un elemento en un conjunto ordenado de tamaño n (n par), por medio de una búsqueda binaria, se cumple que f(n) = f(n/2) + 2 '], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-77,['Ejemplo de funcion generatriz'],['Se tiene una bolsa con 5 canicas amarillas, 4 rojas y 5 blancas. Se eligen 1, 3 ó 5 amarillas, 2, 3 ó 4 rojas y 1, 4 ó 5 blancas, ¿de cuántas formas se pueden elegir 10 canicas?. Función generatriz del primer paso (elección de canicas amarillas) A1(z)=z+z^3+z^5. Función generatriz del 2º paso (canicas rojas) A2(z)=z^2+z^3+z^4. Función generatriz del paso 3 (canicas blancas) A3(z)=z+z^4+z^5. El coeficiente de z^10 en el producto A1*A2*A3, que es 4, es la respuesta a la pregunta'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-78,['Ejemplo de funcion generatriz'],['Se reparten 25 canicas entre 5 niños, recibiendo cada uno al menos 3 canicas. ¿De cuántas formas se pudo hacer la entrega? El orden de la distribución no es significativo. Así tenemos 5 pasos, consistiendo el paso i en la entrega de al menos 3 canicas al niño i. La función generatriz del paso i es z^3+z^4+…+z^25, y la f. generatriz compuesta es (z^3+z^4+…+z^25). El coeficiente de z^25 en este producto es la respuesta pedida. Este coeficiente es el mismo si lo calculamos en (z^3+z^4+…+z^25+…)^25 y ahí es más fácil de calcular. (Aunque por los métodos combinatorios sabemos que la respuesta es C(14,4)) '], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-79,['Ejemplo de funcion generatriz'],['¿Cuál es el nº de soluciones enteras de x1+x2+…+xn=k, con las condiciones ai ≤ xi ≤ bi?. La función generatriz para la elección del tamaño de la variable i es Ai (z) = Z^ai + Z^(ai+1) + .... + Z^bi. Así la función generatriz del problema es A1(z)A2(z)…An(z) y el coeficiente de z^k  en este producto es el nº de soluciones buscado.'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-80,['Ejemplo de funcion generatriz'],['Función generatriz para el problema de calcular el nº de formas de alcanzar franqueo de n euros con sellos de 2, 3 y 5 euros. Llamemos an a dicho nº de formas. Primero elegimos una cierta cantidad de sellos de 2 euros, luego los de 3 euros y, finalmente, los de 5 euros. Como cada sello de 2 euros añade 2 al valor total, la función generatriz de la 1ª elección es 1+z^2+z^4+… Análogamente la función generatriz para el 2º paso (elección del nº de sellos de 3 euros) es 1+z^3+z^6+…, y para el tercer paso (elección del nº de sellos de 5 euros) 1+z^5+z^10+… La función generatriz de an es (1+z^2+z^4+…)*(1+z^3+z^6+…)*(1+z^5+z^10+…). Si nos preguntan por el nº de formas de obtener 20 euros debemos calcular el coeficiente de z^20 en ese producto.'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-81,['Ejemplo de funcion generatriz'],['Hallar el nº de elecciones posibles de 30 juguetes de 10 tipos distintos si: (a) al menos deben elegirse dos de cada clase (b) se eligen entre 2 y 5 de cada clase. Solucion: a) La función generatriz para la elección de cada tipo es z^2+z^3+… Por tanto, la función generatriz del problema es (z^2+z^3+z^4+…)^10 y se quiere calcular el coeficiente de z^30. Este es el coeficiente de z^30 en z^20(1+z+z^2+…)^10, es decir el coeficiente de z^10 en (1+z+z^2+…)^10, que es C(19,10). b) La función generatriz es (z^2+z^3+z^4+z^5)^10 = z^20(1+z+z^2+z^3)^10 = z^20((1+z+…)-(z^4+z^5+…))^10 = z^20*((1+z+z^2+…)^10*(1-z^4)^10 = z^20 * (1+z+z^2+…)^10*(1-10z^4+C(10,2)z^8 + …)^10. De nuevo buscamos el coeficiente de z^30 que llamando w =(1+z+z^2+…)10 será:(coef de z10 en w ) - 10*(coef de z^6 en w) + 45 *(coef. de z^2 en w) , es decir,C(19,10) - 10C(15,6) + 45C(11,2).'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-82,['Ejemplo de funcion generatriz'],['El entrenador y los 25 jugadores de un equipo aportan dinero a un fondo común para bebidas obteniéndose en total 20 euros. Sabiendo que cada jugador aportó 0 ó 1 euro, y el entrenador 0, 2 ó 4 euros, ¿de cuántas formas se pudo obtener la cantidad total? La función generatriz es (1+z^2 +z^4)*(1+z)^25 y es pregunta por el coeficiente de z^20. Este coeficiente será (coef de z^20 en(1+z)^25) + (coef de z^18 en (1+z)^25) + (coef de z^16 en (1+z)^25) es decir, C(25,20)+C(25,18)+C(25,16) .'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-83,['Función generatriz exponencial'],['Estas funciones se utilizan, por ejemplo, para contar permutaciones con repetición limitada o distribuciones de objetos distintos, es decir, sucesiones donde el orden es importante. Se llama función generatriz exponencial de la sucesión A = (a0, a1, a2, …, ak, …) a la serie de potencias E(z)= a0+ a1*z+ (a2*z^2)/2! + …+ ak*z^k//k! + … .'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-84,['Ejemplo de funcion generatriz exponenecial'],['Hallar el nº de sucesiones de longitud ocho que pueden formarse usando 1, 2 ó 3 a; 2, 3 ó 4 b; y 0, 2 ó 4 c. (Ahora el orden sí es importante). La función generatriz exponencial para la elección de a es E(z)= z/1! + z^2/2!+z^3/3!. La función generatriz exponencial para la elección de b es E(z)=z^2/2!+z^3/3!+z^4/4!. La función generatriz exponencial para la elección de c es E(z)= 1+ z^2/2! +z^4/4!. El nº de sucesiones buscado es el coeficiente de z^8/8! en el producto de las funciones anteriores.'], 20/20, ['Casanova basado en http://ldc.usb.ve/~carrasquel/recFG.pdf']).
pr(0027-85,['¿Cuántas ristras de 6 bits hay que comiencen con 1 y acaben con 00?'],['Este ejercicio trata claramente de Variaciones con Repetición. Las ristras buscadas son del tipo 1-XXX-00, donde X puede ser 0 ó 1. Además hay que tener en cuenta el orden en que aparecen los dígitos binarios, p. ej. la ristra 1-001-00 se considera diferente de la 1-010-00. Por tanto, el número de ristras es el de posibles grupos XXX, esto es, V3^2 = 2^3 = 8. Si los escribimos, tendremos: 1-000-00, 1-001-00, 1-010-00, 1-100-00, 1-111-00, 1-011-00, 1-101-00 y 1-110-00. Notemos que, como 3 > 2, obligatoriamente habrá un bit con nombre repetido en la sucesión XXX. Notamos también que el total de ristras de 6 bits es V6^2 = 2^6 = 64.'], 20/20, ['Casanova Basado en http://www.dma.ulpgc.es/profesores/pacheco/ColeccionDeEjercicios01.pdf']).
pr(0027-86,['A un partido de fútbol asisten 6543 espectadores (de pago). Demostrar que hay por lo menos 17 que cumplen años el mismo día del año.'],['Como el año tiene 365 días (si no es bisiesto, claro), hay que distribuir a los 6543 espectadores en 365 casillas. Como 6543 > 365, en alguna casilla habrá más de uno (he aquí el famoso principio en acción). Dado que 6543:365 = 17,92…, encontraremos al menos un día en el que cumplen años más de 17 espectadores. Nota importante: El ejercicio asegura que existe algún día en el que hay más de 17 cumpleañeros simultáneos entre los espectadores: Perfectamente, podrían todos cumplir años el mismo día, y lo pedido seguiría siendo cierto'], 20/20, ['Casanova basado en http://www.dma.ulpgc.es/profesores/pacheco/ColeccionDeEjercicios01.pdf']).
pr(0027-87,['¿Cuantos numeros naturales existen menores que 10^6, cuyas cifras sean todas distintas?'],['Soluci´on. Si n < 106 , n tiene 6 o menos cifras. Consideramos por separados los numeros de 1, 2, 3, 4, 5 y 6 cifras.  De 1 cifra hay 9 numeros. De 2 cifras hay 9 * 9 (son de la forma ab con 1 ≤ a ≤ 9, 0 ≤ b ≤ 9, a =! b). De 3cifras hay 9 * 9 * 8 (son de la forma abc con 1 ≤ a ≤ 9, 0 ≤ b ≤ 9, 0 ≤ c ≤ 9, a, b, c distintos). Analogamente, de 4 cifras hay 9*9*8*7, de 5 cifras hay 9 * 9 * 8 * 7 * 6 y de 6 cifras hay 9 * 9 * 8 * 7 * 6 * 5. Asi, la solucion es 9 + 9 * 9 + 9 * 9 * 8 + 9 * 9 * 8 * 7 + 9 * 9 * 8 * 7 * 6 + 9 * 9 * 8 * 7 * 6 * 5 = 168.570.'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-88,['¿Cuantos enteros m del 1 al 1000 no son divisibles por 3?'],['Los enteros m entre 1 y 1000 divisibles por 3 son de la forma 3k con 1 ≤ k ≤ 333. Asi, hay 333 enteros del 1 al 1000 divisibles por 3. Entonces habra 1000−333 = 667 enteros del 1 al 1000 no divisibles por 3.'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-89,['Demuestra que si se eligen 5 puntos cualesquiera en un cuadrado de lado 2, al menos dos de ellos se encuentran a una distancia no superior a √2.'],['Si tomamos un cuadrado y lo dividmos en cruz haciendo una cruz. Si consideramos como objetos los 5 puntos y como cajas la subdivision del cuadrado en 4 partes, como hay mas objetos que cajas, existiran dos objetos en una misma caja, es decir, existiran dos puntos en una de esas 4 regiones. Entonces, su distancia sera menor que la diagonal de la region cuadrada en la que estan, que mide √2.'], 20/20, ['Casanova basado http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-90,['¿Cuantos numeros de tres cifras distintas tienen todas ellas impares? ¿y pares?'],['Los n´umeros de 3 cifras son de la forma abc con 1 ≤ a ≤ 9, 0 ≤ b ≤ 9, 0 ≤ c ≤ 9. Si todas las cifras son impares y distintas, hay 5 * 4 * 3 posibilidades. Si todas las cifras son pares y distintas, hay 4 * 4 * 3 posibilidades.'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-91,['Se extraen, con reemplazamiento y ordenadamente, cinco cartas de una baraja. ¿En cuantas extracciones hay al menos un rey? ¿En cuantas extracciones hay al menos un rey o un as?'],['El numero de extracciones ordenadas de 5 cartas con reemplazamiento es 40^5. Si ninguna de ellas es un rey, el numero de extracciones posibles es 365. Por tanto, el numero de extracciones en las que hay al menos un rey es 40^5 − 36^5. Por otra parte, el numero de extracciones ordenadas de 5 cartas con reemplazamiento en las que no hay ni reyes ni ases es 32^5 . Por tanto, el numero de extracciones en las que hay al menos un rey o un as es 40^5 − 32^5.'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-92,['Se han de pintar las habitaciones de la casa que se muestra en la figura, de forma que las habitaciones que est´an conectadas por una puerta tengan colores distintos. ¿De cuantas maneras puede pintarse si se dispone de n colores?'],['Si pintamos primero la habitacion A, tenemos n colores disponibles. Para B tendremos n − 1 (cualquiera menos el utilizado para A). Para C tendremos n − 2 (cualquiera menos los utilizados para A y B). Finalmente, para D tendremos n − 1 (cualquiera menos el utilizado para C). Por tanto, el numero de maneras en que puede pintarse la casa es n * (n − 1) * (n − 2) * (n − 1).'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-93,['Lanzando un dado 5 veces ¿cuantos resultados diferentes pueden obtenerse, si se tiene en cuenta el orden de lanzamiento?'],['Son las variaciones (porque se tiene en cuenta el orden) con repeticion (porque puede salir el mismo resultado en diferentes tiradas) de 6 elementos (los 6 resultados posibles que pueden obtenerse al lanzar un dado) de 5 en 5 (el n´umero de veces que se tira el dado). Asi, el numero de resultados diferentes que pueden obtenerse es V(6, 5) = 65'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-94,['Lanzando 5 dados indistinguibles entre si ¿cuantos resultados diferentes pueden obtenerse?'],['Son las combinaciones (porque los dados son indistinguibles y los lanzamos a la vez) con repeticion (porque puede salir el mismo resultado en diferentes tiradas) de 6 elementos (los 6 resultados posibles que pueden obtenerse al lanzar un dado) de 5 en 5 (el numero de veces que se tira el dado). Asi, el numero de resultados diferentes que pueden obtenerse es C(6,5) = 252'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-95,['Dadas 5 vocales y 4 consonantes, ¿cuantas palabras de 2 vocales y 2 consonantes distintas se pueden formar teniendo en cuenta que en cada palabra no figuran dos consonantes seguidas?'],['Si denotamos por V a vocal y C a consonante, hay 3 ordenaciones posibles de las vocales y consonantes en la palabra: CV CV, CV V C, V CV C. En cada uno de los 3 casos, el n´umero de palabras de 2 vocales y 2 consonantes distintas es 5*4*4*3 (5 posibilidades para la primera vocal, 4 posibilidades para la segunda vocal, 4 posibilidades para la primera consonante y 3 posibilidades para la segunda consonante). Asi, el numero de palabras de 2 vocales y 2 consonantes distintas en las que no figuran dos consonantes seguidas es 3*(5*4*4*3)'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-96,['Un circuito electrico posee 10 interruptores. Teniendo en cuenta que cada interruptor tiene dos posiciones {1, 0}: a) ¿cuantos estados diferentes puede tener el circuito seg´un la posicion de los interruptores? b) ¿cuantos estados tienen tres interruptores en posicion 1 y el resto en posicion 0?'],['a) Son las variaciones (porque los interruptores son distintos) con repetici´on (porque dos interruptores pueden estar en el mismo estado) de 2 elementos (los 2 estados posibles para cada interruptor) de 10 en 10. Ası, el numero de resultados diferentes que pueden obtenerse es V(2, 10) = 2^10. b) El numero de estados con tres interruptores en posicion 1 y el resto en posicion 0 es C10,3 (pues basta escoger los 3 interruptores que estaran en posicion 1 (el resto de interruptores estaran forzosamente en posicion 0).'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-97,['¿Cuantas palabras de 13 letras pueden formarse con las letras de la palabra CLASIFICACION?'],['Son permutaciones con repeticion, P13^(3+3+2+1+1+1+1+1) = 13!/(3! * 3! * 2)'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-98,['¿De cuantas maneras se pueden distribuir 10 canicas identicas entre 6 ni˜nos? ¿Y si las canicas son todas ellas de distintos colores?'],['El numero de maneras de distribuir 10 canicas identicas entre 6 ni˜nos coincide con el umero de soluciones de la ecuacion x1 + x2 + x3 + x4 + x5 + x6 = 10 (xi ≥ 0 representa el numero de canicas que se le dan al ni˜no iesimo), que es (6, 10). Si las canicas son todas ellas de distintos colores, el numero de maneras de distribuirlas es 6^10 (cada canica se puede repartir a cualquiera de los 6 ni˜nos).'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-99,['¿Cuantos numeros hay en el conjunto {1, 2, ..., 1000} tales que la suma de sus dıgitos sea 5?'],['Son las soluciones de la ecuacion x1 + x2 + x3 = 5 (xi ≥ 0), que es CR(3, 5) = 21. Podemos enumerarlos todos: 5, 14, 23, 32, 41, 50, 104, 113, 122, 131, 140, 203, 212, 221, 230, 302, 311,320, 401, 410, 500.'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-100,['¿Cuantos numeros enteros entre 1000 y 9999 satisfacen que la suma de sus digitos es 9?'],['Son las soluciones de la ecuaci´on x1 + x2 + x3 + x4 = 9 (x1 ≥ 1, x2, x3, x4 ≥ 0), que es CR(4, 8) = 165'], 20/20, ['Casanova basado en http://www.fiwiki.org/images/0/08/MD11-12EjerciciosResueltosTema4.pdf']).
pr(0027-101,['Probar que cualquier subconjunto de seis elementos del conjunto S = {1, 2, . . . , 9} debe contener dos elementos cuya suma sea 10.'],['Hay 4 maneras para que dos elementos (diferentes) de S sumen 10: 1 + 9 = 10, 2 + 8 = 10, 3 + 7 = 10, 4 + 6 = 10. Consideremos los siguientes subconjuntos de S: S1 = {1, 9}, S2 = {2, 8}, S3 = {3, 7}, S4 = {4, 6}, S5 = {5}. Todo elemento de S esta en algun Subconjunto. Sea A un subconjunto de S con seis elementos. Eso significa que existe algun Si con dos o mas elementos de A. Como los Sj tienen dos o un elemento, el subconjunto Si que tiene dos o mas elementos de A contiene exactamente dos elementos de A, entonces no es S5 y es S1, S2, S3 o S4. Luego, hay dos elementos de A que suman 10, como queriamos demostrar.'], 20/20, ['Casanova basado en http://www.fing.edu.uy/~eleonora/Recopilacion/Archivos/NotasEnsenanza/matematicaDiscreta05.pdf']).
pr(0027-102,['Un número telefónico consta de siete cifras enteras. Supongamos que la primera cifra debe ser un número entre 2 y 9, ambos inclusive. La segunda y la tercera cifra deben ser números entre 1 y 9, ambos inclusive. Cada una de las restantes cifras es un número entre 0 y 9, ambos inclusive. ¿Cuántos números de teléfono distintos pueden formarse con estas condiciones? '],['Para la primera cifra tenemos 8 casos. Para la segunda y tercera juntas son V(9,2) y las restantes serán V(10,4). En consecuencia el número de teléfonos es 8*9^2*10^4= 6.480.000'], 20/20, ['Casanova basado en http://www.iesxunqueira1.com/Departamentos/Documentos/mate_discreta.pdf']).
pr(0027-103,['Una empresa produce cerraduras de combinación. Cada combinación consta de tres números enteros del 0 al 99, ambos inclusive. Por el proceso de construcción de las cerraduras cada número no puede aparecer más de una sola vez en la combinación de la cerradura. ¿Cuántas cerraduras diferentes pueden construirse? '],['Una posible combinación sería 1, 23, 87 que sería distinta de 23, 1, 87, por lo que importa el orden. Por otra parte nos dicen que cada número no puede aparecer más de una sola vez, por lo que no hay repetición. Se trata de V(100,3) = 100*99*98.'], 20/20, ['Casanova basado en http://www.iesxunqueira1.com/Departamentos/Documentos/mate_discreta.pdf']).
pr(0027-104,[' Resolver la siguiente relacione de recurrencia homogénea, con sus condicion inicial'],['An = 4A(n-1) - 4A(n-2) , n>=2 A0= 6, A1=8. Es una relación de recurrencia homogénea cuya ecuación característica es r^2-4r+4=0 que tiene una raíz doble: 2. Por tanto su solución general es c(2)^n+c’n(2)^n. Según las condiciones inciales: 6 = c; 8 = 6*2+c’*2; c’=-2. La solución es por tanto: An = 2^(n+1) * (3-n) n>=0. '], 20/20, ['Casanova basado en http://www.iesxunqueira1.com/Departamentos/Documentos/mate_discreta.pdf']).
%pr(0027-105,['Sea an el número de palabras de longitud n formadas con los dígitos {0,1}, que no tienen dos ceros consecutivos. Encontrar una relación de recurrencia para calcular An y resolverla. '],['Descartamos A0 pues no tiene sentido para nosotros. Sea A1=2*(0 y 1) A2= 3 *(01, 10, 11). Sea an el número de palabras pedidas en esas condiciones. Llamemos An1 a las acabadas en 1 de las An. Llamemos An0 a las acabadas en 0 de las An. Es obvio que An = An1 + An0. Si acaba en 1, la cifra anterior puede ser 1 o 0, con lo que An1 = n-1. Si acaba en 0, la cifra anterior solo puede ser 1, con lo que An0 = A(n-1)*1 = n-2. Por tanto An = An-1 + An-2 , para n>2. La resolvemos: Su ecuación característica es r^2-r-1=0, cuyas soluciones son (1+-5^1/2)/2. La solución general es del tipo An = [(5+3*5^1/2)10]*[((1+5^1/2)/2)^n]+[(5-3*5^1/2)/10]*[((1-5^1/2)/2)^n]. para n>=1.'], 20/20, ['Casanova basado en http://www.iesxunqueira1.com/Departamentos/Documentos/mate_discreta.pdf']).











