%Ayuda a Pitagoras
%Nivel 5 Combinatoria
%Modificado Por Ender Puentes
%Diciembre, 2016

pr(0001-67,['¿Cuántas', 'sumas', 'diferentes', 'de', 'dos', 'sumandos', 'cada', 'una', 'se', 'pueden', 'obtener', 'con', 'los', 'números', '4,', '6,', '10,', '15,', '25,', 'y', '28?'], ['15', 'sumas ', '10', 'sumas ', '25', 'sumas ', '6', 'sumas '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-68,['Se', 'dispone', 'de', '5', 'jugos', 'de', 'fruta', 'diferentes;', '¿Cuántos', 'sabores', 'se', 'pueden', 'formar', 'mezclándolos', 'en', 'la', 'misma', 'porción?'], ['31', 'sabores ', '23', 'sabores ', '32', 'sabores ', '10', 'sabores '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-69,['Las', 'diagonales', 'de', 'un', 'polígono', 'se', 'obtienen', 'uniendo', 'dos', 'vértices', 'no', 'adyacentes,', 'sabiendo', 'esto;', '¿Cuántas', 'diagonales', 'tiene', 'un', 'dodecágono?'], ['54', 'diagonales ', '58', 'diagonales ', '45', 'diagonales ', '64', 'diagonales '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-70,['Ernesto', 'tiene', '8', 'amigos', 'y', 'desea', 'invitarlos', 'a', 'cenar,', 'pero', 'sólo', 'puede', 'invitar', 'a', '5', 'simultáneamente,', '¿Cuántos', 'grupos', 'distintos', 'de', 'invitados', 'puede', 'tener?'], ['56', 'grupos ', '52', 'grupos ', '64', 'grupos ', '48', 'grupos '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-71,['Se', 'dispone', 'de', '11', 'personas', 'para', 'la', 'limpieza', 'de', 'un', 'local', 'comercial,', 'se', 'requiere', 'formar', 'grupos', 'de', '4', 'integrantes', 'para', 'dividir', 'el', 'trabajo;', '¿Cuántos', 'grupos', 'diferentes', 'pueden', 'hacerse?'], ['330', 'grupos ', '410', 'grupos ', '300', 'grupos ', '320', 'grupos '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-72,['Carlos', 'asiste', 'a', 'un', 'festival', 'de', 'comida', 'donde', 'hay', '10', 'platos', 'de', 'su', 'agrado,', 'si', 'solo', 'le', 'pueden', 'servir', '4', 'de', 'estos;', '¿Cuántas', 'comidas', 'diferentes', 'puede', 'servirse?'], ['210', 'comidas ', '200', 'comidas ', '180', 'comidas ', '240', 'comidas '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-73,['Con', 'los', 'números', '24,', '35,', '50,', '55', 'y', '60;', '¿Cuántas', 'sumas', 'diferentes', 'pueden', 'hacerse', 'donde', 'intervengan', 'los', '5', 'números?'], ['1', 'suma ', '2', 'suma ', '3', 'suma ', '4', 'suma '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-74,['¿De', 'cuántas', 'maneras', 'se', 'puede', 'escoger', 'un', 'comité,', 'compuesto', 'por', '3', 'hombres', 'y', '2', 'mujeres,', 'de', 'un', 'grupo', 'de', '7', 'hombres', 'y', '5', 'mujeres?'], ['350', 'maneras ', '330', 'maneras ', '320', 'maneras ', '335', 'maneras '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0000-1, ['Este', 'siempre', 'sera', 'el', 'final', 'del', 'juego'], ['a','b ', 'c ', 'd '], ['0', '0', '0', '0'], ['Ender', 'Puentes']). 
pr(0000-000, ['No', 'borrar'], ['a ', 'b ', 'c ', 'd '], ['0', '0', '0', '0'], ['Ender', 'Puentes']). 
pr(0000-000, ['Este', 'siempre', 'sera', 'el', 'final', 'del', 'juego'], ['a ', 'b ', 'c ', 'd '], ['0', '0', '0', '0'], ['Ender', 'Puentes']). 
