%Ayuda a Pitagoras
%Nivel 4 Induccion
%Modificado Por Ender Puentes
%Diciembre 2016

pr(0001-104,['Sean', '+', 'y', '*', 'operaciones', 'definidas', 'sobre', 'un', 'conjunto', 'A', 'donde', '(A,*)', 'es', 'un', 'grupo', 'abeliano,', '(A,+)', 'es', 'un', 'semigrupo', 'y', 'se', 'cumple', 'que', '[a', '(*)', '(b', '(+)', 'c)]', '=', 'a', '(*)', 'b', '(+)', 'a', '(*)', 'c];', '¿Es', '(T,*,+)', 'un', 'anillo?'], ['Verdadero ', 'Falso ', 'Verdadero ', 'Falso '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-105,['Sea', '(B,+,·)', 'un', 'anillo;', '¿Qué', 'condiciones', 'debe', 'cumplir', 'para', 'que', 'sea', 'un', 'anillo', 'unitario?'], ['Debe', 'tener', 'un', 'elemento', 'tal', 'que', 'a·e=a,', 'es', 'decir,', 'un', 'elemento', 'neutro', 'respecto', 'a', 'la', 'segunda', 'operación ', 'Debe', 'tener', 'un', 'elemento', 'tal', 'que', 'a·(-a)=e,', 'es', 'decir,', 'un', 'elemento', 'neutro', 'respecto', 'a', 'la', 'segunda', 'operación ', 'Debe', 'tener', 'un', 'elemento', 'tal', 'que', 'a·e=a,', 'es', 'decir,', 'un', 'elemento', 'inverso', 'respecto', 'a', 'la', 'segunda', 'operación ', 'Debe', 'tener', 'un', 'elemento', 'tal', 'que', 'a·(-a)=e,', 'es', 'decir,', 'un', 'elemento', 'inverso', 'respecto', 'a', 'la', 'segunda', 'operación '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-106,['Sea', '(A,+,*)', 'un', 'anillo;', '¿Qué', 'condiciones', 'debe', 'cumplir', 'para', 'que', 'sea', 'un', 'anillo', 'conmutativo?'], ['Debe', 'cumplirse', 'la', 'propiedad', 'conmutativa', 'respecto', 'a', 'la', 'segunda', 'operación,', 'a*b', '=', 'b*a ', 'Debe', 'cumplirse', 'la', 'propiedad', 'conmutativa', 'respecto', 'a', 'la', 'segunda', 'operación,', 'a*(b+c)', '=', 'b*a+c*ac ', 'Debe', 'cumplirse', 'la', 'propiedad', 'conmutativa', 'respecto', 'a', 'la', 'segunda', 'operación,', 'a*b', '=', 'b-a ', 'Debe', 'cumplirse', 'la', 'propiedad', 'conmutativa', 'respecto', 'a', 'la', 'segunda', 'operación,', 'a*b', '=', 'b*(-a) '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-107,['Sea', 'R', 'un', 'anillo;', 'Decimos', 'que', 'a', '∈', 'R,', 'es', 'una', 'unidad', 'si', 'existe', 'un', 'b', '∈', 'R', 'tal', 'que', 'ab', '=', '1;', 'Escriba', 'todas', 'la', 'unidades', 'de', 'ℤ'], ['1,-1 ', '0,-1 ', '1,0 ', '0,0 '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-108,['Escriba', 'todas', 'las', 'unidades', 'del', 'conjunto', 'de', 'los', 'números', 'racionales', '(Q)'], ['Q', '-', '{0} ', 'Q+ ', 'Q- ', 'Q', '-', '{1} '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-109,['Sea', '(R,#,·)', 'un', 'anillo;', 'Si', '3#8', '=', '20,', 'donde', '3', 'y', '8', '∈', 'R;', '¿Cuánto', 'es', '8#3?'], ['11', 'debido', 'a', 'que', '(R,#)', 'es', 'un', 'grupo', 'abeliano ', '20', 'debido', 'a', 'que', '(R,#)', 'es', 'un', 'grupo', 'abeliano ', '24', 'debido', 'a', 'que', '(R,#)', 'es', 'un', 'grupo', 'abeliano ', 'No', 'se', 'puede', 'determinar '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-110,['Sea', '(A,#,$)', 'un', 'anillo;', 'Si', '3$9', '=', '50,', '3', 'y', '9', '∈', 'A;', '¿Cuánto', 'es', '9$3?'], ['No', 'se', 'puede', 'determinar ', '27 ', '3 ', '12 '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
pr(0001-111,['Sea', '(D,#,*)', 'un', 'anillo;', 'Si', 'Δ#♦', '=', '○,', 'Δ', 'y', '♦', '∈', 'D;', '¿Cuánto', 'es', '♦#Δ?'], ['○ ', 'Δ ', '♦ ', 'No', 'se', 'puede', 'determinar '], ['20 ', '0 ', '0 ', '0 '], ['María', 'Daniela', 'Baptista', 'Theuerkauf']).
