%Ayuda a Pitagoras
%Nivel 2 Conjuntos
%Modificado Por Ender Puentes
%Diciembre 2016

pr(0008-1,['¿', 'Qué', 'es', 'un', 'conjunto', '?'], ['Es', 'un', 'grupo', 'de', 'objetos', 'finitos', 'o', 'infinitos', 'que', 'se', 'relacionan', 'entre', 'si ', 'Es', 'un', 'grupo', 'de', 'objetos', 'infinitos', 'que', 'se', 'relacionan', 'entre', 'si ', 'Es', 'un', 'grupo', 'de', 'objetos', 'finitos', 'que', 'se', 'relacionan', 'entre', 'si ', 'Es', 'un', 'grupo', 'de', 'objetos', 'finitos', 'o', 'infinitos', 'que', 'interactuan', 'entre', 'si '], ['20 ', '0 ', '0 ', '0 '], ['Javier Solsona', 'Tomado de guía de conjuntos del profesor Carlos Domingo']).
pr(0001-14,['Determine', 'si', 'los', 'conjuntos', 'A', 'y', 'B', 'son', 'iguales;', 'A', '=', '{2n² : n ∈ ℕ y 0 ≤ n ≤ 3}', 'B', '=', '{2,0,8,18}'], ['Iguales ', 'Distintos ', 'Iguales ', 'Distintos '], ['20 ', '0 ', '0 ', '0 '], ['María Daniela Baptista Theuerkauf']).
pr(0001-19,['Determine', 'si', 'los', 'conjuntos', 'A', 'y', 'B', 'son', 'iguales;', 'A', '=', '{x ∈ ℕ : 1 < x < 6}', 'B', '=', '{n : n ∈ ℕ y 1 ≤ n ≤ 6}'], ['Distintos ', 'Iguales ', 'Distintos ', 'Iguales '], ['20 ', '0 ', '0 ', '0 '], ['María Daniela Baptista Theuerkauf']).
pr(0001-26, ['Indique', 'la', 'cardinalidad', 'del', 'conjunto', 'A', '=', '{2,3,6,4,1,8,2,8,56,45,34,56,89,12,21}'], ['12 ', '11 ', '10 ', '21'], ['20 ', '0 ', '0 ', '0 '], ['María Daniela Baptista Theuerkauf']).
pr(0001-43,['Determine', 'el', 'dominio', 'de', 'la', 'siguiente', 'relación;', 'R', '=', '{(1, 1),', '(1, 2),', '(1, 3),', '(1, 4),', '(2, 2),', '(2, 4),', '(3, 3),', '(4, 4)}'],['{1,2,3,4} ', '{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16} ', '{1,2,3,4,5,6,7,8} ', '{0,1,2,3} '], ['20 ', '0 ', '0 ', '0 '], ['María Daniela Baptista Theuerkauf']).
pr(0001-44,['Determine', 'el', 'rango', 'de', 'la', 'siguiente', 'relación;', 'R', '=', '{(n, 2n)', ':', 'n ∈ ℕ U {0}}'],['Los números pares ', 'Los números impares ', 'Los números primos ', 'Los números complejos '], ['20 ', '0 ', '0 ', '0 '], ['María Daniela Baptista Theuerkauf']).
pr(0008-6,['¿', 'Todo', 'conjunto', 'tiene', 'un', 'complemento', '?'], ['Si', 'este', 'se', 'define', 'como', 'el', 'identificador', 'del', 'conjunto', 'con', 'una', 'tilde', 'al', 'lado ', 'Si', 'este', 'se', 'define', 'como', 'el', 'subconjunto', 'del', 'mismo ', 'Si', 'este', 'se', 'define', 'como', 'el', 'identificador', 'del', 'conjunto', 'con', 'una', 'llave', 'al', 'lado ', 'Si', 'este', 'se', 'define', 'como', 'el', 'identificador', 'del', 'conjunto', 'con', 'una', 'asterisco', 'al', 'lado '], ['20 ', '0 ', '0 ', '0 '], ['Javier Solsona', 'Tomado de guía de conjuntos del profesor Carlos Domingo']),
pr(0008-7,['¿', 'Cuál', 'es', 'el', 'complemento', 'del', 'conjunto', 'universal', 'E', 'y', 'del', 'conjunto', 'B={x / x>7 y x ∈ ℕ}', 'respectivamente?'], ['El', 'complemento', 'de', 'E', 'es', 'el', 'conjunto', 'vacio', '', 'y', 'el', 'complemento', 'de', 'B', 'es', 'B(tilde)={0,1,2,3,4,5,6} ', 'El', 'complemento', 'de', 'E', 'es', 'el', 'conjunto', 'no', 'vacio', 'y', 'el', 'complemento', 'de', 'B', 'es', 'B(tilde)={0,1,2,3,4,5,6} ', 'El', 'complemento', 'de', 'E', 'es', 'el', 'conjunto', 'vacio', '', 'y', 'el', 'subconjunto', 'de', 'B', 'es', 'B(tilde)={0,1,2,3,4,5,6} ', 'El', 'complemento', 'de', 'E', 'es', 'el', 'conjunto', 'vacio', '', 'y', 'la', 'relaciòn', 'de', 'B', 'es', 'B(tilde)={0,1,2,3,4,5,6} '], ['20 ', '0 ', '0 ', '0 '], ['Javier Solsona', 'Tomado de guía de conjuntos del profesor Carlos Domingo']).
pr(0009-10, ['Notacion', 'de', 'un', 'conjunto'], ['Un', 'conjunto', 'se', 'denota', 'con', '{} ', 'Un', 'conjunto', 'se', 'denota', 'con', '() ', 'Un', 'conjunto', 'se', 'denota', 'con', '[] ', 'Un', 'conjunto', 'se', 'denota', 'con', '"" '], ['20 ', '0 ', '0 ', '0 '], ['Urbaez tomado de: http://nux.ula.ve/mathematica/conjuntos.pdf']).
pr(0009-12, ['Conjunto de los planetas del sistema solar'], ['El', 'conjunto', 'de', 'los', 'planetas', 'del', 'sistema', 'solar', 'se', 'define', 'como', 'P', '=', '{Mercurio,', 'Venus,', 'Tierra,', 'Marte,', 'Júpiter,', 'Saturno,', 'Urano,', 'Neptuno} ', 'El', 'conjunto', 'de', 'los', 'planetas', 'del', 'sistema', 'solar', 'se', 'define', 'como', 'P', '=', '{Mercurio,', 'Venus,', 'Tierra,', 'Marte,', 'Júpiter,', 'Saturno,', 'Urano,', 'Neptuno,', 'Luna} ', 'El', 'conjunto', 'de', 'los', 'planetas', 'del', 'sistema', 'solar', 'se', 'define', 'como', 'P', '=', '{Mercurio,', 'Venus,', 'Tierra,', 'Marte,', 'Júpiter,', 'Saturno,', 'Urano,', 'Neptuno,', 'Pluton} ', 'El', 'conjunto', 'de', 'los', 'planetas', 'del', 'sistema', 'solar', 'se', 'define', 'como', 'P', '=', '{Venus,', 'Tierra,', 'Marte,', 'Júpiter,', 'Saturno,', 'Urano,', 'Neptuno} '], ['20 ', '0 ', '0 ', '0 '], ['Urbaez tomado de: http://nux.ula.ve/mathematica/conjuntos.pdf']).